[package]
name = "rust"
version = "0.1.0"
authors = ["Kent Seneres <kseneres@medrhythms.com>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib", "cdylib"]

[dependencies]
jni = { version = "0.13.1", default-features = false }
